name: random-cpp
version: 0.2.0
homepage: https://github.com/morloclib/random-cpp
synopsis: C++ implementations for random number generation
description: C++ implementations for random number generation
category: numeric
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/random-cpp
bug-reports: https://github.com/morloclib/random-cpp
